version: "3.7"
services:
    db:
        image: postgres
        environment: 
            POSTGRES_PASSWORD: barebone-db-pw
            POSTGRES_USER: barebone-db-user
            POSTGRES_DB: postgres-barebone
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    web:
        image: barebone
        depends_on:
            - db
        ports:
            - '4000:4000'
